# Generated by Django 6.0.1 on 2026-02-11 12:53

import mapsearch.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default=mapsearch.user.models.generate_api_key, max_length=128),
        ),
    ]
